[package]
name = "ruforo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12"
actix-session = "0.5.0-beta.4"
actix-web = "4.0.0-beta.12"
actix-web-actors = "4.0.0-beta.7"
env_logger = "0.9.0"
lettre = "0.10.0-rc.4"
