[package]
name = "ruforo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12"
actix-session = "0.5.0-beta.4"
actix-web = "4.0.0-beta.13"
actix-web-actors = "4.0.0-beta.7"
argon2 = "0.3"
askama = { git = "https://github.com/djc/askama", default-features = false, features = ["with-actix-web", "mime", "mime_guess"] }
askama_actix = { git = "https://github.com/djc/askama" }
bytes = "1"
bytestring = "1"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15"
env_logger = "0.9"
futures = { version = "^0.3" }
futures-util = { version = "^0.3" }
lettre = "0.10.0-rc.4"
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros" ], default-features = false }
serde = "1"
uuid = { version = "0.8", default-features = false, features = ["v4"] }

[dev-dependencies]
actix-test = "0.1.0-beta.7"
